### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by codegyeon** [codegyeon/hanghae_Blog#6]
- http body 에 값이 하나만 들어올 경우
  {"password" : "password"} 이렇게 작성할 경우 400에러가 뜬다
  "password" 로 보내니 서버에서 인식하였다.
  그래서 jackson 이 한 개의 필드는 인식을 못하는게 아닐까? 라는 생각이 들었고 찾아보았지만 아직 해결을 못했다(해결 x)

- ResponseDto 에러
  Repository에서 list 객체를 ResponseDto 타입으로 받으려고 하니 에러가 발생하였다. localdatetime 을 인식을 못하는 상태였다.
  아 그전에 내가 왜 ResponseDto로 받으려고 했냐면 post 객체에 password 라는 필드가 존재하는데 findAll 를 하게되면 password 정보까지 유출이 되어서
  password 를 제외한 모든 필드를 가져오려고 ResponseDto를 짜보았는데 에러가 발생하였다.
  일단 password 에 @jsonignore 어노테이션을 사용하여 값을 못가져오도록 설정해놓았다.
-----> Dto 필드 이름을 객체 필드와 맞추지 않아 에러가 생긴거였다.(해결 o)

**Comment by Nhahan** [comment]
http body 에 값이 하나만 들어올 경우
{"password" : "password"} 이렇게 작성할 경우 400에러가 뜬다
"password" 로 보내니 서버에서 인식하였다.
그래서 jackson 이 한 개의 필드는 인식을 못하는게 아닐까? 라는 생각이 들었고 찾아보았지만 아직 해결을 못했다(해결 x)


필드 개수와 무관할텐데 혹시 아직 해결 안된 이슈신가요?

**Comment by codegyeon** [comment]
ReponseDto 의 기본생성자를 생성안해서 생긴 문제였습니다!
